### ISSUE TITLE
请问 座位剩余数量如何实现

### ISSUE THREAD

**Issue by mutouzhang** [MummyDing/Awesome-Campus#24]
这个教室还剩多少座位 是实时采集的吗，通过人工不太现实，毕竟还是有一定的时效性，难道是通过摄像头？如果是这个思路的话具体流程能说明下吗？知乎路过。

**Comment by KevinWu1993** [comment]
哈哈，你想得太复杂了，图书馆的数据是来自图书馆里面刷卡上座的刷卡机的

**Comment by mutouzhang** [comment]
图书馆的刷卡机数据对外开放？走你自己的服务器吗？还是说图书馆自己的服务器对外开放api?

**Comment by MummyDing** [comment]
@mutouzhang  这个是和课表什么的一样的，通过模拟登陆抓取数据进行解析。

**Comment by KevinWu1993** [comment]
都没有，图书馆自习室的数据是通过模拟登录，获取到cookie然后通过解析html取得数据的，具体实现你可以参考以下：

- [登录获取cookie](https://github.com/MummyDing/Awesome-Campus/blob/dev/app/src/main/java/cn/edu/jxnu/awesome_campus/support/utils/login/SelfStudyRoomLoginUtil.java)
- [自习室位置DAO](https://github.com/MummyDing/Awesome-Campus/blob/dev/app/src/main/java/cn/edu/jxnu/awesome_campus/database/dao/library/SelfStudySeatLeftDAO.java)
- [数据解析](https://github.com/MummyDing/Awesome-Campus/blob/dev/app/src/main/java/cn/edu/jxnu/awesome_campus/support/htmlparse/libary/SelfStudySeatLeftParse.java)

**Comment by mutouzhang** [comment]
了解，受教了，请关闭问题
