### ISSUE TITLE
关于 .gitignore

### ISSUE THREAD

**Issue by life2015** [MummyDing/Awesome-Campus#29]
### 推荐添加这两个 
``` 
*.iml
.DS_Store
```

**Comment by MummyDing** [comment]
好的，感谢建议。
刚开始建仓库的时候选的默认忽略规则也没管它，空了加上。

**Comment by life2015** [comment]
还有一个小地方就是app模块的gradle里面
android.support:design包引入了两次依赖（而且版本不一样）
虽然gradle会帮自动筛选，改一下会更好
